#!/usr/bin/env python3
"""Generate licenses/sbom.cdx.json (CycloneDX 1.5) and licenses/THIRD_PARTY_NOTICES.md
from the hash-pinned locks (host: requirements.lock, sandbox image: runtime/python/requirements.lock)
and the installed distributions' own metadata. No network access."""
from __future__ import annotations

import datetime
import hashlib
import json
import re
import uuid
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pins(lock: Path):
    for line in lock.read_text().splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)==([^\s;\\]+)", line)
        if match:
            yield match.group(1), match.group(2)


def license_of(name: str) -> str:
    try:
        meta = metadata.metadata(name)
    except metadata.PackageNotFoundError:
        return "UNKNOWN (not installed on this host)"
    expression = meta.get("License-Expression")
    if expression:
        return expression
    classifiers = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return " OR ".join(sorted(set(classifiers)))
    text = (meta.get("License") or "").strip().splitlines()
    return text[0][:80] if text else "UNKNOWN"


def main() -> None:
    components = []
    notices = ["# Third-party notices", "", "Generated by `scripts/generate_sbom.py` from the pinned lock files. "
               "Licenses are read from each distribution's own metadata.", ""]
    for scope, lock in (("host (requirements.lock)", ROOT / "requirements.lock"),
                        ("sandbox runtime image (runtime/python/requirements.lock)", ROOT / "runtime" / "python" / "requirements.lock")):
        notices += [f"## {scope}", "", "| Package | Version | License |", "|---|---|---|"]
        for name, version in pins(lock):
            lic = license_of(name)
            components.append({"type": "library", "name": name, "version": version, "purl": f"pkg:pypi/{name.lower()}@{version}",
                               "licenses": [{"license": {"name": lic}}], "properties": [{"name": "scope", "value": scope}]})
            notices.append(f"| {name} | {version} | {lic} |")
        notices.append("")
    notices += ["## Container base image", "", "`python:3.12-slim` pinned by digest in `runtime/python/Dockerfile` (Debian + CPython, PSF-2.0 and Debian package licenses).", "",
                "## Copied code", "", "No third-party source code is vendored into this repository; design inspiration (DeepSeek Harness, "
                "Aider, smolagents, mini-SWE-agent) is architectural only.", ""]
    sbom = {"bomFormat": "CycloneDX", "specVersion": "1.5", "serialNumber": f"urn:uuid:{uuid.uuid4()}", "version": 1,
            "metadata": {"timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                         "component": {"type": "application", "name": "ai-coding-harness", "version": "0.1.0"}},
            "components": components}
    (ROOT / "licenses").mkdir(exist_ok=True)
    (ROOT / "licenses" / "sbom.cdx.json").write_text(json.dumps(sbom, indent=2) + "\n")
    (ROOT / "licenses" / "THIRD_PARTY_NOTICES.md").write_text("\n".join(notices))
    print(f"{len(components)} components")


if __name__ == "__main__":
    main()
